name: Make release
description: Make release

inputs:
  tag_name:
    description: Set product to compile
    required: true
    type: string
  target_name:
    description: Set chipcode module to compile
    required: true
    type: string
  branch:
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: |
        echo "tag_name=${{ inputs.tag_name }}"
        echo "target_name=${{ inputs.target_name }}"
        sudo chown $(whoami) -R $(pwd)
      shell: bash
    - run: |
        git fetch origin feature/github_workflow
        git checkout origin/feature/github_workflow -- .github build
      shell: bash
