name: Make release
description: Make release

inputs:
  tag_name:
    description: Set product to compile
    required: true
    type: string
  target_name:
    description: Set chipcode module to compile
    required: true
    type: string
  branch:
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: |
        sudo chown $(whoami) -R ${GITHUB_WORKSPACE}
      shell: bash
    - run: |
        git fetch origin feature/github_workflow_build_cl
        git checkout origin/feature/github_workflow_build_cl -- .github build
      shell: bash
