name: Make release
description: Make release

inputs:
  tag_name:
    description: Set product to compile
    required: true
    type: string
  target_name:
    description: Set chipcode module to compile
    required: true
    type: string
  branch:
    required: true
    type: string
  hardware_version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: |
        sudo chown $(whoami) -R ${GITHUB_WORKSPACE}
      shell: bash
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        lfs: true
        fetch-depth: 0
    - run: |
        cd  ${GITHUB_WORKSPACE}

        git reset --hard
        git clean -fdx

        git merge origin/c10qm_v1 --no-edit

        git checkout origin/feature/github_workflow -- .github build

        git format-patch -p1 1a7f2024bb1139e48e1f1e85762c57b2b3a84f0c
        if patch -p1 < 0001-sbl-support-disable-ramdump.patch --dry-run; then
            echo "Patch applied successfully"
            patch -p1 < 0001-sbl-support-disable-ramdump.patch
        else
            echo "Failed to apply patch"
            exit -1
        fi

        bash build/build.sh ${{ inputs.tag_name }} ${{ inputs.hardware_version }} c10qm nonhlos release
        zip -r mdm9607_release_${{ inputs.target_name }}_${{ inputs.tag_name }}.zip binaries_out
        echo "${{ github.token }}" > .token.txt
        gh auth login --with-token < .token.txt
        gh release upload "Release_MDM9607_${{ inputs.tag_name }}" mdm9607_release_*.zip --clobber --repo ${{ github.repository }}
        gh auth logout -u github-actions[bot]
        rm .token.txt
      shell: bash
      env:
        GH_TOKEN: ${{ env.GH_TOKEN }}
