name: Manual build
description: Manual build

inputs:
  tag_name:
    required: true
    type: string
  hardware_version:
    required: true
    type: string
  production:
    required: true
    type: string
  build_module:
    required: true
    type: string
  disable_ramdump:
    type: boolean
    required: false
  upload:
    required: true
    type: string
  release_type:
    required: true
    type: string
  pull_request:
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: |
        echo "${{ github.token }}" > .token.txt
        gh auth login --with-token < .token.txt
      shell: bash

    - run: |
        gh pr comment 406 \
              --repo ${{ github.repository }} \
              --body "Your build is ready at this link, take it as***le"
        echo "test" > BIGFILE.zip
        gh pr review 406 --body "Output for verification:" --comment BIGFILE.zip

      shell: bash

    - run: |
        gh auth logout -u github-actions[bot]
        rm -f .token.txt
      shell: bash

