name: Create release
description: Create release

inputs:
  tag_name:
    description: Set product to compile
    required: true
    type: string
  branch:
    required: true
    type: string
  overwrite_tags:
    description: 'Overwrite tag if existed'
    type: boolean
    required: false

runs:
  using: composite
  steps:
    - run: |
        echo "${{ github.token }}" > .token.txt
        gh auth login --with-token < .token.txt
        cd ${GITHUB_WORKSPACE} && echo "GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}" && ls
        echo "Check tag ${TAG_NAME} is exist or not"
        if [[ $( gh release list --repo ${{ github.repository }} | grep "Release_MDM9607_${{ inputs.tag_name }}" ) ]]
        then
          if [[ ${{ inputs.overwrite_tags }} == "true" ]]
          then
            echo "Removing existing tag: ${{ inputs.tag_name }} "
            gh release delete --repo ${{ github.repository }} "Release_MDM9607_${{ inputs.tag_name }}" -y
          else
            echo "Tag exists:"Release_MDM9607_${{ inputs.tag_name }}" "
            exit 1
          fi
        fi
        echo "Creating new tag: ${TAG_NAME} ..."
        gh release create "Release_MDM9607_${{ inputs.tag_name }}" --target ${{ inputs.branch }} --repo ${{ github.repository }}
        gh auth logout -u github-actions[bot]
        rm .token.txt
      shell: bash
      env:
        GH_TOKEN: ${{ env.GH_TOKEN }}

