name: Create release
description: Create release

inputs:
  tag_name:
    description: Set product to compile
    required: true
    type: string
  branch:
    required: true
    type: string
  overwrite_tags:
    description: 'Overwrite tag if existed'
    type: boolean
    required: false

runs:
  using: composite
  steps:
    - run: |
        TAG_NAME="Release_MDM9607_${{ inputs.tag_name }}"
        echo "${{ github.token }}" > .token.txt
        gh auth login --with-token < .token.txt
        cd ${GITHUB_WORKSPACE}
        echo "Check tag ${TAG_NAME} is exist or not"
        if [[ $( gh release list --repo ${{ github.repository }} | grep  ${TAG_NAME} ) ]]
        then
          if [[ ${{ inputs.overwrite_tags }} == "true" ]]
          then
            echo "Removing existing tag: ${{ inputs.tag_name }} "
            gh release delete \
                --repo ${{ github.repository }} \
                 ${TAG_NAME} -y
          else
            echo "Tag exists: ${TAG_NAME} "
            gh auth logout -u github-actions[bot]
            rm .token.txt
            exit 0
          fi
        fi
        echo "Creating new tag: ${TAG_NAME} ..."
        gh release create  ${TAG_NAME} \
                          --generate-notes \
                          --target ${{ inputs.branch }} \
                          --repo ${{ github.repository }}
        gh auth logout -u github-actions[bot]
        rm .token.txt
      shell: bash
      env:
        GH_TOKEN: ${{ env.GH_TOKEN }}

